version: "3"
services:
  dropwizard:
    image: michaelvk1994/ipsenh-studievolg
    ports:
     - "8090:8090"
    volumes:
      - "./volume-dropwizard/configuration.yml:/opt/dropwizard/configuration.yml"
#     - volume-dropwizard:/dropwizard
    depends_on:
      - postgres
  sonarqube:
      image: sonarqube
      ports:
        - "9000:9000"
      depends_on:
        - postgres
      environment:
        - sonar.jdbc.url=jdbc:postgresql://136.144.152.131:5432/sonardb
        - SONARQUBE_JDBC_USERNAME=sonar
        - SONARQUBE_JDBC_PASSWORD=sonarQube2017@
      volumes:
        - sonarqube_conf:/opt/sonarqube/conf
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: HSleiden2017@
      POSTGRES_DBNAME: IPSENH-Studievolg
      POSTGRES_DBUSER: hsleiden2017
      POSTGRES_DBPASS: hsleiden2@
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    image: nginx
    links:
     - dropwizard
     - sonarqube
    ports:
     - "80:80"
    volumes:
     - volume-nginx-conf.d:/etc/nginx/conf.d
     - volume-nginx-log:/var/log/nginx
volumes:
  postgres-data:
  volume-nginx-conf.d:
  volume-nginx-log:
  volume-dropwizard:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
