FROM openjdk:8-jre
MAINTAINER Michael “s1089455@student.hsleiden.nl”
RUN mkdir -p /opt/dropwizard

COPY . /opt/dropwizard

RUN apt-get update && apt-get install maven
WORKDIR /opt/dropwizard
RUN mvn install