FROM java:8
MAINTAINER Michael “s1089455@student.hsleiden.nl”

#Make the directory
RUN mkdir -p /opt/dropwizard
COPY . /opt/dropwizard

# make opt/dropwizard the working directory (current directory)
WORKDIR /opt/dropwizard

#Install maven
RUN apt-get update
RUN apt-get -y install maven

# Install dependencies of POM
RUN mvn install