apiName: "IPSENH Studievolg API"

server:
  registerDefaultExceptionMappers: false
  rootPath: /api/*
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
  
database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: hsleiden2017

  # the password
  password: hsleiden2@

  # the JDBC URL
  url: jdbc:postgresql://136.144.152.131:5432/IPSENH-Studievolg

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the timeout before a connection validation queries fail
  validationQueryTimeout: 3s

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute
